// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3lSuEcQ31V1v-_a4JyBbiRsKNmUtiy2E',
    appId: '1:279354222102:web:6feb172aa2ee63bcbcb737',
    messagingSenderId: '279354222102',
    projectId: 'go-hadi',
    authDomain: 'go-hadi.firebaseapp.com',
    storageBucket: 'go-hadi.firebasestorage.app',
    measurementId: 'G-QVP70YX5ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvx66U9XRlXOIus4_u7HUlRVhQsanG4g',
    appId: '1:279354222102:android:ec5592faed51d2dabcb737',
    messagingSenderId: '279354222102',
    projectId: 'go-hadi',
    storageBucket: 'go-hadi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTADOnj4WBV2xxcvI2huEHVZyBvEmFys',
    appId: '1:279354222102:ios:ac15a67d0ef4af20bcb737',
    messagingSenderId: '279354222102',
    projectId: 'go-hadi',
    storageBucket: 'go-hadi.firebasestorage.app',
    iosBundleId: 'com.arrijal.hadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTADOnj4WBV2xxcvI2huEHVZyBvEmFys',
    appId: '1:279354222102:ios:ac15a67d0ef4af20bcb737',
    messagingSenderId: '279354222102',
    projectId: 'go-hadi',
    storageBucket: 'go-hadi.firebasestorage.app',
    iosBundleId: 'com.arrijal.hadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3lSuEcQ31V1v-_a4JyBbiRsKNmUtiy2E',
    appId: '1:279354222102:web:0ce995ebb26796f8bcb737',
    messagingSenderId: '279354222102',
    projectId: 'go-hadi',
    authDomain: 'go-hadi.firebaseapp.com',
    storageBucket: 'go-hadi.firebasestorage.app',
    measurementId: 'G-N1FFRE77F4',
  );
}
